### ISSUE TITLE
Not functioning with the current wordpress build

### ISSUE THREAD

**Issue by hssetrp** [PRDeltoid/Petpoint-Webservices#1]
I'd like to say, first, that I am so, so, so grateful you built this and put it out to the public.  The shelter I work for has SO many pets going through it every day it would be amazing to cut our time by using our petpoint data on or own website instead of re-uploading all the details again.  Obviously there are iframes available for use, but, well, you probably know why i hesitate to go that route.   

Anyway, I hope it isn't too forward to ask for some help using this.  If you're not working on this plug-in anymore, or don't have time for this, I understand. But something seems to have gone wrong and I'm not advanced enough to figure out what.  Here's what I did:
1. Installed the master build plugin from the zip.
2. c/p the markup into the proper pages (they were already created), adding in a text line inside the div that reads "this will display if the plugin is not working"
3. posted those URLS into the plugin settings page, as well as the Auth. Key from our petpoint's searchable pet iframe config page; saved
4. saved "changes" to the permalinks
5. cleared my browser cache just in case

When I pulled up the pages the only thing displayed was the text.  I re-saved the changes to the permalinks, let it sit about twenty minutes, and still nothing.  I pulled the plug-in, loaded in the dev build instead, and went through the process again.  Nadda. 

Our site is running wordpress 4.2.2.  I'm currently installing the old 4.0 build, which seems to be what was "up to date" when you built the plugin, to test it there.  This will likely take a while given our internet service isn't the best.  I'll report on it later, if you're interested.

Once again, thank you for putting this up at all. Even if it can't be fixed for our application, it was still a great idea--especially given that no one else seems to have even tried this!  It's a great asset for the animal rescue community.

**Comment by hssetrp** [comment]
Update:  Got the plug-in working mostly.  There was an issue at first with both the dog / cat pages pulling all animals rather than by species, but that got sorted once I realize you HAVE to specify which rooms are which. 

That said, the view animals isn't working at all.  I'm trying to fix it and will post here when/if I manage it, but otherwise it seems like this project has been abandoned.

**Comment by hssetrp** [comment]
OK just for the record, I figured out what was wrong:  As the plugin is currently written you cannot assign the "View Animal" pages as a child page, it HAS to be on the first level.  Otherwise, the individual pets will never show up. 

Otherwise, I was wrong, this plugin functions perfectly fine with the current wordpress (4.3.1.)

**Comment by kikit2** [comment]
I know your post is from a few years ago but I am needing help on this.  I am BRAND NEW to Wordpress and I have read some things on how to set this up but I'm lost as a ball in high weeds!  I am building a site for free for a non-profit animal shelter. They currently use Pet Point and want to continue to use it, while having the new WP site pull that data from Pet Point (if that makes sense).  I just need some instructions on how to make that work.  I would appreciate any help you could give me.
