### ISSUE TITLE
None of the pages are working properly, but the cat and dog pages both pull the full inventory of animals regardless of type

### ISSUE THREAD

**Issue by Finagar** [PRDeltoid/Petpoint-Webservices#13]
So basically my cat page shows all cats and dogs and the same thing with my dog page. The actual animal profile page doesn't show any info. Do you think you could helo me out?

**Comment by PRDeltoid** [comment]
Are both your dogs and cats housed in the same room? 

I am realizing there is a bug where I had not considered that dogs and cats might be in the same Location. The cat/dog pages only filter based on location, not on the animal species. 

I am going to work on making it separate by species as well so this doesn't happen (if this does happen to be your issue). In the meantime, if you still use this plugin, I've been able to set up a test site and created some updates that fix some common bugs. You may want to install the new version and see if that fixes the issue as well.

**Comment by PRDeltoid** [comment]
Created a central issue for this bug here: #15
