### ISSUE TITLE
"Description" misspelled on view animal pages

### ISSUE THREAD

**Issue by hssetrp** [PRDeltoid/Petpoint-Webservices#2]
Noticed a couple days ago that when viewing individual animals the title "Description" is misspelled as "desciption."  I've been pouring through the code trying to find the issue--I did find and fix two or three instances of the typo, as well as others, but nothing I do seems to aggregate the fix to the plugin itself.  Is this something in the code itself, or perhaps it's an issue carried over from petpoint? @PRDeltoid 

ETA:  Found the problem.  It's in the config file.

**Comment by hssetrp** [comment]
Also worth mentioning, the petpoint webservice links have changed.  They need to be updated from "www." to "ws." or they won't work.

**Comment by PRDeltoid** [comment]
Sounds like a simple change. I'll commit a fix soon.

May I ask what organization you work for? I'm surprised someone else is finding use for this plugin!

**Comment by hssetrp** [comment]
I'm with the Humane Society of Southeast Texas.  This plugin's an absolute life saver!  We were pretty much stuck with those tacky i-frames until I found this.  So very glad you shared it.

**Comment by PRDeltoid** [comment]
Don't know why I didn't fix this when I changed the web services link. Sorry about that. This has been fixed.
