### ISSUE TITLE
On single pet page, animal data is not loading in IE 11-

### ISSUE THREAD

**Issue by guanyixi** [PRDeltoid/Petpoint-Webservices#4]
It looks like some javascript functions on view_animal.js are not supported by IE 11-. It works fine in all other browsers including IE Edge.

**Comment by PRDeltoid** [comment]
Sorry it has taken me so long to get to this. Do you still use this plugin? If so, can you provide me a link to the webpage where it is being used? Through private message is fine. My company no longer uses this plugin (or WordPress), so I have no way of easily testing the issue without a webpage running the plugin.

**Comment by guanyixi** [comment]
Oh, hey Taylor, thank you for responding. Actually the shelter no longer
uses petspoint any more. You plugin did inspire me to explore how WordPress
plugins work, and I was able to make it work the way it needed to. Thank
you for sharing the plugin. I am sure other people still can use it.


Brooklyn

**Comment by PRDeltoid** [comment]
That's awesome :)
