### ISSUE TITLE
How to get Pet Point info into WordPress

### ISSUE THREAD

**Issue by kikit2** [PRDeltoid/Petpoint-Webservices#5]
I am BRAND NEW to Wordpress and I have read some things on how to set this up but I'm lost as a ball in high weeds! I am building a site for free for a non-profit animal shelter. They currently use Pet Point and want to continue to use it, while having the new WP site pull that data from Pet Point (if that makes sense). I just need some instructions on how to make that work. I would appreciate any help you could give me.

**Comment by PRDeltoid** [comment]
You can enter your PetPoint information into WordPress through the plugin settings menu. You can get to that menu from your WordPress Administration Panel by hover over Settings and then select "PP Webservices Settings" (if this doesn't work, let me know. You may have a different version of WordPress from me). You also want to make sure to set up the pages you are going to be displaying the data on by adding `<div id="animal"></div>` to them. Make sure everything matches exactly! This whole process will fail if there are any typos. 

You can view more detailed instructions in the README file for this repository. Alternatively, PetPoint provides a (slightly less featureful/customizable) version of this, that requires much less setup, if you'd prefer that route.
