### ISSUE TITLE
Adoptable Dogs/Cats Pages Don't Show Only Dogs/Cats

### ISSUE THREAD

**Issue by jachavez06** [PRDeltoid/Petpoint-Webservices#7]
As title says, both Adoptable Dogs Page and Adoptable Cats Page show dogs + cats. 

All animals have correct species labeling in Petango.

**Comment by Amandahdm** [comment]
@jachavez06 Were you ever able to fix, or find a fix, for this?

**Comment by jachavez06** [comment]
No :/, mind lending some insight?

**Comment by PRDeltoid** [comment]
I apologize for not getting to this sooner. My notifications were muted for this project and I didn't realize it had pending issues. 

I realize it's almost 2 years late and I assume you've moved on, but if you still want to give this plugin a try, I am happy to help troubleshoot your issue. 

My first question is, have you set the "Dogs Page" and "Cats Page" URLs in the 'PP Webservice Settings' menu to the pages you generated?

**Comment by PRDeltoid** [comment]
Created a central issue for this bug here: #15
